# Where things are
source:       .
# destination:  ./finalSite
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes
pages: _pages
collections:
  posts:
    output:   true
header_image: header2.jpg

# Variables
title: Rafael Umino Nakanishi
email: rafael.umino.nakanishi@gmail.com
description: > # this means to ignore newlines until "twitter:"
 Personal blog and resume
twitter: rnaka_
github: rnakanishi
tumblr: rnakanishi
instagram: rnaka_
artstation: uryousuke
linkedin: rafael-nakanishi-2650bb17
quote: Os acertos não serão muitos nessa vida. Mas é bom que treinemos com eles para que possamos nos aperfeiçoar

# Handling Reading
# theme: jekyll-theme-slate
safe:         false
include:      [".htaccess","_pages"]
exclude:      ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
# markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 10
future:      false
unpublished: false

# Plugins
whitelist: []
# plugins_dir:   []

# Conversion
markdown: kramdown
highlighter: rouge
linenos: true;
lsi: false
excerpt_separator: "\n\n"
incremental: false
parse_block_html: true

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname
show_dir_listing: false


# Outputting
permalink:     date
paginate_path: blog/page:num
timezone:      null

quiet:    false
verbose:  false
defaults: []

liquid:
  error_mode: warn

gems: [jekyll-paginate, jekyll-textile-converter]
paginate: 5

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  hard_wrap:      false
  footnote_nr:    1
  input:          GFM
  syntax_highlighter: rouge
  hard_wrap: false
  syntax_highlighter_opts:
    span: false
    block:
      line_numbers: true
      start_line: 1
  parse_block_html: true
